language: python

python:
  - "2.7"

sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

env:
  global:
  - VERSION="9.0" TESTS="0" LINT_CHECK="0" TRANSIFEX="0"
  - TRANSIFEX_USER='transbot@odoo-community.org'
  # travis for docs build
  - secure: "lazdZGpkqFTQiu44grYAqKcaGh0cVTBlrHcBxxs43K/OH4Uc2AjMBty83zKc0ZgzizrNOsfK3Z3UHLmTNI92Vi3PtgGzA9dUmiReGO6QcE9P31Geg4pN/1Fwosv6aSpG3hejJJ8ZYpMbEPJkZyjTVpdM2r1VEcqEvFQ2xR5bEUg="
  # transifex
  - secure: "WspsOy3m3Arreqs+f8QAnKOCPbXfpO7TeUJEfJSMehMh8I+bR1KFZM0CUfKxNOT9mrbt94J9VzF3knC2p4P/lUWr24USJ27FgOScnTz/PQTjZfjdXDefGdhCCx3QgIzI/mj751BYp2FMBYXEvjaBSycerWJ+AP+OKVEdf44Lgp0="

  matrix:
  - LINT_CHECK="1"
  - TRANSIFEX="1"
  - TESTS="1" ODOO_REPO="odoo/odoo"
  - TESTS="1" ODOO_REPO="OCA/OCB"
  - DOCS="1"

virtualenv:
  system_site_packages: true

install:
  - git clone --depth=1 https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install PyPDF2==1.18
  - pip install unidecode
  - pip install pycountry
  - pip install suds-jurko==0.6
  - pip install sphinx sphinx_bootstrap_theme sphinx-intl odoo-sphinx-autodoc

script:
  - if [ "$DOCS" != "1" ] ; then travis_run_tests; fi
  - if [ "$DOCS" == "1" ] ; then ./.travis_build_doc; fi

after_success:
  - if [ "$DOCS" != "1" ] ; then travis_after_test_success; fi
  - if [ "$DOCS" == "1" ] ; then ./.travis_push_doc; fi
